import type { Metadata } from "next";
import "./globals.css";
import { SidebarInset, SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/base/app-sidebar";
import { Toaster } from "@/components/ui/toaster";
import { Alexandria } from "next/font/google";

import DynamicBreadcrumbs from "@/components/base/dynamic-breadcrumbs ";
import { Separator } from "@/components/ui/separator";

const alexandria = Alexandria({
  weight: "400",
  subsets: ["arabic"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl">
      <body className={alexandria.className}>
      <SidebarProvider>
          <AppSidebar />
          <SidebarInset>
            <header className="flex h-16 shrink-0 items-center gap-2 transition-[width,height] ease-linear group-has-[[data-collapsible=icon]]/sidebar-wrapper:h-12">
              <div className="flex items-center gap-2 px-4">
                <SidebarTrigger className="-mr-1"/>
                <Separator orientation="vertical" className="ml-2 h-4" />
                <DynamicBreadcrumbs />
              </div>
            </header>
            {children}
          </SidebarInset>
        </SidebarProvider>
        <Toaster />
      </body>
    </html>
  );
}
